### ISSUE TITLE
Error response from daemon: configured logging driver does not support reading 

### ISSUE THREAD

**Issue by follmann** [michaelshobbs/dokku-syslog#3]
**EDIT:** Ok, the deploy error might stem from something else. Is the daemon error expected? Thanks!

Excellent plugin!

It's all smooth, except sometimes I start getting the following error on deploys:

```
remote: [1G[1G-----> Finalizing build        
remote: [1G[1G       Caching versions for future builds        
remote: [1G[1G       Creating runtime environment        
remote: [1G[1G       Using release configuration from last framework (Phoenix).        
remote: [1G[1G       [1G-----> Discovering process types        
remote: [1G[1G       Procfile declares types -> web        

remote: [1G-----> Releasing my_app (dokku/my_app:latest)...        

remote: [1G-----> Deploying my_app (dokku/my_app:latest)...        
remote: [1G-----> Attempting to run scripts.dokku.predeploy from app.json (if defined)        

remote: [1G-----> Running './deploy/pre-deploy' in app container        

remote: execution of './deploy/pre-deploy' failed!        
remote: [1G       Error response from daemon: configured logging driver does not support reading 
```

The only fix is to uninstall the plugin. Redeploy and reinstall the plugin.

I'm running dokku v0.11.3

Thanks!

**Comment by michaelshobbs** [comment]
It's definitely not expected and is coming from docker itself. I wonder if there's something buggy about docker's `syslog` driver. Let me know what you find out. 

EDIT: I was wrong. The daemon error is expected.

**Comment by michaelshobbs** [comment]
Oh wait! What is happening in `./deploy/pre-deploy`? What happens if you run `docker logs <some container id/name>`? I don't think the syslog driver supports `docker logs` since everything is going to syslog.

**Comment by michaelshobbs** [comment]
Hrm it would seem that this plugin is incompatible with dokku now.....

from: https://docs.docker.com/config/containers/logging/configure/#supported-logging-drivers
```
Limitations of logging drivers
The docker logs command is not available for drivers other than json-file and journald.
```

EDIT: I am able to deploy with this plugin installed. It just prints that error and continues though. The actual source of you problem is this: `remote: execution of './deploy/pre-deploy' failed!` Something is failing in your `predeploy` script.

**Comment by michaelshobbs** [comment]
Closing as this is not an issue with this plugin. @follmann feel free to hop on dokku's slack for help with your `predeploy` script

**Comment by follmann** [comment]
Thanks for spending the time investigating!

After my edit, I wasn't entirely sure this plugin causes the issue.  I found a modified docker upstart conf that is supposed to fix the pre-deploy error. Sorry for the confusion...

**Comment by michaelshobbs** [comment]
No worries at all
